### ISSUE TITLE
Add attributes to /existing/ properties?

### ISSUE THREAD

**Issue by LordMike** [NdubuisiJr/TypeExtender#1]
Hi,

I found this library from your comment here: https://stackoverflow.com/questions/14663763/how-to-add-an-attribute-to-a-property-at-runtime

The example you provided adds a _new_ property with some attribute - but is it possible to add an attribute to an _existing_ property?

I'm trying to dynamically add some attributes to some models in an ASP.Net site, and have attempted to work off of examples using TypeDescriptors and providers in that, to alter existing properties. It doesn't seem to take though, as the output from `GetType()` does not include my new property. I hoped this library had working code, but couldn't find out how to add to existing properties.. :)

**Comment by NdubuisiJr** [comment]
Hi,

Thanks for coming here. I'm afraid, it is not possible to add an attribute to an existing class or type at runtime. The best you can do is to extend that class, add a new property with the attribute and then work with this new property. The reason it is not possible is because, in order to add a property to a class you need a `PropertyBuilder` object. This object is only returned by the `DefineProperty` method (which creates a new property).

You can checkout this, stackoverflow [post](https://stackoverflow.com/questions/13524426/add-a-property-at-runtime-to-an-existing-object-by-using-propertybuilder), if you haven't already.

Thanks

**Comment by LordMike** [comment]
I feared as much, that thread also touches on what I experienced: `You cannot add real (reflection) properties ..`

Anyhoo. I've lowered my ambitions and resolved my issue in a different manner. :)
